# Generated by Django 5.2.8 on 2025-12-04 23:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Cuenta')),
                ('initial_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Inicial')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('annual_rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Tasa Anual')),
                ('clabe', models.CharField(max_length=18, unique=True, verbose_name='CLABE Interbancaria')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Número de Tarjeta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cuenta de Ahorro',
                'verbose_name_plural': 'Cuentas de Ahorro',
                'ordering': ['name'],
            },
        ),
    ]
