# Generated by Django 5.2.8 on 2025-11-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_expense_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='remaining_months',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
