# Generated by Django 5.2.8 on 2025-11-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_expense_is_paid_expense_paid_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='expense',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
    ]
